Resources:
   CMSApi:
    Type: "AWS::ApiGateway::RestApi"
    Properties:
      Description: "test Api"
      Name: "CMS-opeartion-api"  
   PostMethod: 
    Type: "AWS::ApiGateway::Method"
    Properties: 
     RestApiId: !Ref CMSApi
     ResourceId: 
       Fn::GetAtt: 
        - "CMSApi"
        - "RootResourceId"
     HttpMethod: "POST"
     RequestParameters:
      method.request.header.Cookie: False
     AuthorizationType: "NONE"
     Integration: 
       Type: "MOCK"
       IntegrationResponses: 
          - ResponseParameters:
             method.response.header.Set-Cookie: "integration.response.body.Set-Cookie"
             method.response.header.Access-Control-Allow-Credentials: "true"
             method.response.header.Access-Control-Allow-Origin: "'https://s3.amazonaws.com'"
            ResponseTemplates:
              application/json: "$input.body"
#       PassthroughBehavior: "NEVER"
#       IntegrationHttpMethod: "POST"
#       Uri: 
#        !Sub | 
#          - arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${!lambdaFunctionArn}/invocations
#          - {lambdaFunctionArn: arn:aws:lambda:ap-southeast-1:216184389560:function:my-cms-aws-cms-Controller}
#       RequestTemplates:
#         "application/json": "{#if($input.params('Cookie') && $input.params('Cookie') != '') {'body': $input.body, 'token': '$input.params('Cookie')'}#else{'body': $input.body}#end}"
     MethodResponses:
       - ResponseModels:
           application/json: Empty
         ResponseParameters:
           method.response.header.Set-Cookie: False
           method.response.header.Access-Control-Allow-Credentials: False
           method.response.header.Access-Control-Allow-Origin: False
         StatusCode: "200"
          
Outputs:
   ApiId:
     Description: API ID
     Value: !Ref CMSApi
   ApiUrl:
     Description: API Url
     Value: 
       !Sub | 
         - https://${!apiId}.execute-api.${AWS::Region}.amazonaws.com/prod # for non presudo variable or custom variable use #${!varaibleName}
         - { apiId: !Ref CMSApi }
   ApiPermissionsUri:
     Description: API Permissions Uri
     Value: 
       !Sub |
        - arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${!apiId}/*/POST/
        - { apiId:  !Ref CMSApi }
    
      